### ISSUE TITLE
nan repeats with invalid waypoint

### ISSUE THREAD

**Issue by terakoji** [tork-a/rtmros_nextage#123]
waypointに絶対とどかないような値が入ると、以下のようにエラーがでる。

hrpsys viewerでは腕が消える。

```
[ERROR] [1415423530.956301965, 85.874999999]: Ignoring transform for child_frame_id "LARM_JOINT5_Link" from authority "/hrpsys_state_publisher" because of a nan value in the transform (-nan -nan -nan) (-nan -nan -nan -nan)
[ERROR] [1415423531.012215046, 85.894999999]: Ignoring transform for child_frame_id "LARM_JOINT0_Link" from authority "/hrpsys_state_publisher" because of a nan value in the transform (-nan -nan -nan) (-nan -nan -nan -nan)
[ERROR] [1415423531.012265258, 85.894999999]: Ignoring transform for child_frame_id "LARM_JOINT1_Link" from authority "/hrpsys_state_publisher" because of a nan value in the transform (-nan -nan -nan) (-nan -nan -nan -nan)
[ERROR] [1415423531.012317342, 85.894999999]: Ignoring transform for child_frame_id "LARM_JOINT3_Link" from authority "/hrpsys_state_publisher" because of a nan value in the transform (-nan -nan -nan) (-nan -nan -nan -nan)
[ERROR] [1415423531.012363061, 85.894999999]: Ignoring transform for child_frame_id "LARM_JOINT4_Link" from authority "/hrpsys_state_publisher" because of a nan value in the transform (-nan -nan -nan) (-nan -nan -nan -nan)
[ERROR] [1415423531.012405777, 85.894999999]: Ignoring transform for child_frame_id "LARM_JOINT5_Link" from authority "/hrpsys_state_publisher" because of a nan value in the transform (-nan -nan -nan) (-nan -nan -nan -nan)
```

**Comment by garaemon** [comment]
`/joint_states`にnanが入っていますか?

hrpsys内部で問題が生じているように見えますね

-- ryohei

**Comment by DaikiMaekawa** [comment]
こちらのソースで動かした時のエラーのようです。
https://github.com/ros-japan-users/nextage_moveit_planning_execution/blob/master/scripts/moveit_command_sender.py

executeメソッドがブロックしない(?)のが問題かと思ったのですがどうでしょうか。

**Comment by 130s** [comment]
http://moveit.ros.org/wiki/Executing_Trajectories_with_MoveIt!#The_Trajectory_Execution_Manager

```
To scale the amount of time to wait (e.g., more than 10%), the 
setAllowedExecutionDurationScaling() function can be called or the 
ROS parameter ~/allowed_execution_duration_scaling can be set. 
```

I haven't tried this yet though.

**Comment by k-okada** [comment]
どなたか再現するコード（xxのlaunchを上げてxxのファイルでXXの指令を送る）を持っていたら，ここに貼り付けていただけると嬉しいです．

**Comment by garaemon** [comment]
おそらく問題は二つありますね
1. moveitがありえない角度を送ってしまっている
2. その関節角をhrpsysが受け取るとhrpsys内部でnanが発生する

その結果としてjoint_statesにnanが載っていると予想できます

2014年11月8日土曜日、Kei Okadanotifications@github.comさんは書きました:

> どなたか再現するコード（xxのlaunchを上げてxxのファイルでXXの指令を送る）を持っていたら，ここに貼り付けていただけると嬉しいです．
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tork-a/rtmros_nextage/issues/123#issuecomment-62250271
> .

## 

from iPhone

**Comment by k-okada** [comment]
@terakoji please provide an information of how to reproduce this problem

**Comment by terakoji** [comment]
再現させようと思ったのですが、久しぶりに起動しようとしたら

```
$ rtmlaunch nextage_ros_bridge nextage_ros_bridge_simulation.launch

Traceback (most recent call last):
  File "/opt/ros/indigo/bin/rtmlaunch", line 28, in <module>
    from openrtm_tools import rtmstart, rtmlaunch
  File "/opt/ros/indigo/lib/python2.7/dist-packages/openrtm_tools/rtmlaunch.py", line 14, in <module>
    from rtshell import rtcon
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rtshell/rtcon.py", line 26, in <module>
    import rtctree.tree
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rtctree/tree.py", line 30, in <module>
    from rtctree.directory import Directory
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rtctree/directory.py", line 26, in <module>
    from rtctree.component import Component
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rtctree/component.py", line 30, in <module>
    import rtctree.sdo
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rtctree/sdo.py", line 26, in <module>
    class RTCObserver(OpenRTM__POA.ComponentObserver):
AttributeError: 'module' object has no attribute 'ComponentObserver'
```

が出てしまいます。なにかわかりますでしょうか？

**Comment by terakoji** [comment]
自己解決しました。　apt-get upgrade したらエラーが消えました。
