### ISSUE TITLE
ACTION REQUIRED: Important update with version 0.6.0 or higher (March, 2015)

### ISSUE THREAD

**Issue by 130s** [tork-a/rtmros_nextage#153]
This is an important message for the NEXTAGE OPEN users (ie. Hironx users are NOT affected).

With the upcoming latest version of the software packages, you'll be required to take an action to apply the following changes.

If you are **NOT** planning to update the software by either one of the following commands, you can stop reading at this point:
- `apt-get` command of Ubuntu
- `git pull` or equivalent commands if you're using the source code version of NEXTAGE OPEN packages

If you have any questions regarding this, please contact us by either one of the followings:
- (Recommended) Post comment on this ticket.
- Ask on the [rtm-ros-robotics mailinglist](https://groups.google.com/forum/#!forum/rtm-ros-robotics|rtm-ros-robotics@googlegroups.com) as usual.
- Sned a direct email to support[ a-t ]opensource-robotics.tokyo.jp to respect privacy
# Users affected

Affected users are those who fit into **BOTH** of these two conditions:
- use either one of the following packages (users usually use both):
  - `nextage_ros_bridge` 0.6.0 or higher
  - `nextage_moveit_config` 0.6.0 or higher
- haven't updated the ControllerBox (QNX) software to 315.2.8 or higher
  - You're likely to fit here if you haven't asked any professional service for the update work.
# Modifications required
- **Modification-a**. Command to run ROS server on your Ubuntu machine needs an extra argument.
  - BEFORE ver. 0.6.0 `roslaunch nextage_ros_bridge nextage_ros_bridge_real.launch`
  - AFTER ver. 0.6.0  `roslaunch nextage_ros_bridge nextage_ros_bridge_real.launch MODEL_FILE:=/opt/jsk/etc/HIRONX/model/main.wrl`
  
  With `MODEL` argument, you're telling the location of 3D model file *_inside *_ of ControllerBox/QNX (so that it's ok that the path you're passing doesn't exist on you Ubuntu machine). Note that you should keep using `HIRONX` for your NEXTAGE robot in this particular command.
- **Modification-b**. If your application uses any of the following method from `NextageClient` class in Python (which is introduced as "`robot`" varibale on `ipython` console in the tutorials), make sure you add an argument `frame_name=None`.
  - [getCurrentPose](http://docs.ros.org/hydro/api/hironx_ros_bridge/html/classhironx__ros__bridge_1_1hironx__client_1_1HIRONX.html#a17afb9d8c83fb9d6b03565b27b7929de)
  - [getCurrentPosition](http://docs.ros.org/hydro/api/hironx_ros_bridge/html/classhironx__ros__bridge_1_1hironx__client_1_1HIRONX.html#a5d3d77ba14a1a38a3cd1763a3dc19f61)
  - [getCurrentRotation](http://docs.ros.org/hydro/api/hironx_ros_bridge/html/classhironx__ros__bridge_1_1hironx__client_1_1HIRONX.html#a07902654de9c39b38d34e45f065c5063)
  - [getCurrentRPY](http://docs.ros.org/hydro/api/hironx_ros_bridge/html/classhironx__ros__bridge_1_1hironx__client_1_1HIRONX.html#ac7c2db48019da907edb0c8dc39c44308)
  - [getReferencePose](http://docs.ros.org/hydro/api/hironx_ros_bridge/html/classhironx__ros__bridge_1_1hironx__client_1_1HIRONX.html#a5c720c0dd42cb572b53ac00c73f2d02d)
  - [getReferencePosition](http://docs.ros.org/hydro/api/hironx_ros_bridge/html/classhironx__ros__bridge_1_1hironx__client_1_1HIRONX.html#ab332daf349e68a2d3932af3ebe3e77da)
  - [getReferenceRotation](http://docs.ros.org/hydro/api/hironx_ros_bridge/html/classhironx__ros__bridge_1_1hironx__client_1_1HIRONX.html#aa550e5acc6aabf6da569f3e63124704c)
  - [getReferenceRPY](http://docs.ros.org/hydro/api/hironx_ros_bridge/html/classhironx__ros__bridge_1_1hironx__client_1_1HIRONX.html#aa6b6616f212c0c7fc74611ecc5ca0655)
  
  Example: 
  - Output from earlier versions:
  
  ```
  In [18]: robot.getCurrentPosition('RARM_JOINT5')
  Out[19]: [0.32484858569580044, -0.1820186913915894, 1.0368028692158924]
  ```
  - Output from version 0.6.0 or higher. Notice the `z` values differ.
  
  ```
  In [18]: robot.getCurrentPosition('RARM_JOINT5')
  Out[18]: [0.32484858569580044, -0.1820186913915894, 0.0668028692158924]
  
  In [1]: robot.getCurrentPosition('RARM_JOINT5', frame_name='WAIST')
  Out[18]: [0.32484858569580044, -0.1820186913915894, 0.0668028692158924]
  
  In [19]: robot.getCurrentPosition('RARM_JOINT5', frame_name=None)
  Out[19]: [0.32484858569580044, -0.1820186913915894, 1.0368028692158924]
  ```

The affecting changes were primarilly made in order to compensate the different height between robots (in their model files, `Hiro` has no base while `NEXTAGE` has) so that uses who have both types of robots couldn't use same code for different robots. Actually these changes provide more solid API in general for Hiro and NEXTAGE, so we hope all users benefit from this. We appreciate any feedback from you.

Isaac from your friendly neighbourhood TORK dev team

---

**EDIT** (3/26/2015): Purpose of this change is to ultimately enhance the usability and stability of the software, by eliminating rather robot-specific portion of codes and applying more common usage. We appreciate your understanding.

**Comment by longjie** [comment]
I cannot find /opt/jsk/etc/HIRONX/modes/main.wrl . Which package does include this file?
I'm using following packages with NEXTAGE OPEN.

ii  ros-hydro-nextage-description              0.6.1-0precise-20150310-0207-+0000 
ii  ros-hydro-nextage-moveit-config            0.6.1-0precise-20150311-1844-+0000
ii  ros-hydro-nextage-ros-bridge               0.6.1-0precise-20150311-1752-+0000 

ii  ros-hydro-hironx-calibration               1.0.28-0precise-20150206-2221-+0000 
ii  ros-hydro-hironx-moveit-config             1.0.28-0precise-20150311-1752-+0000  
ii  ros-hydro-hironx-ros-bridge                1.0.28-0precise-20150311-1725-+0000  
ii  ros-hydro-hironx-tutorial                  1.0.27-0precise-20150204-0535-+0000

**Comment by longjie** [comment]
OK,  /opt/jsk/etc/HIRONX/models/main.wrl sould be the file in the QNX controller.
Anyway I got enomous error after launch such as:

omniORB: ERROR -- the application attempted to invoke an operation
 on a nil reference.
CORBA::SystemException raised by ModelLoader: IDL:omg.org/CORBA/INV_OBJREF:1.0
CORBA::SystemException raised by ModelLoader: IDL:omg.org/CORBA/INV_OBJREF:1.0
omniORB: ERROR -- the application attempted to invoke an operation
 on a nil reference.

**Comment by 130s** [comment]
> OK, /opt/jsk/etc/HIRONX/models/main.wrl sould be the file in the QNX controller.

Thanks for clarification, and yes that's correct. I've updated [my original post](https://github.com/tork-a/rtmros_nextage/issues/153#issue-60846562) to clarify this.

> Anyway I got enomous error after launch such as:
> 
> omniORB: ERROR -- the application attempted to invoke an operation on a nil reference.
> CORBA::SystemException raised by ModelLoader: IDL:omg.org/CORBA/INV_OBJREF:1.0

Are you still able to operate the robot as intended despite the errors?

Also, could you run the following script, and send back the resulted tarball to support[a-t]opensource-robotics.tokyo.jp? This script shouldn't be harmful to any corporate network (please take a look at the code in the URL if necessary).
`curl -sL https://raw.githubusercontent.com/start-jsk/rtmros_common/master/hrpsys_tools/scripts/rtmroswtf.sh | bash -`

**Comment by 130s** [comment]
I'm very sorry that there was a critical mistake.
- WRONG: `AFTER ver. 0.6.0 roslaunch nextage_ros_bridge nextage_ros_bridge_real.launch MODEL:=/opt/jsk/etc/HIRONX/modes/main.wrl`
- CORRECT: `AFTER ver. 0.6.0 roslaunch nextage_ros_bridge nextage_ros_bridge_real.launch MODEL_FILE:=/opt/jsk/etc/HIRONX/model/main.wrl`

**Comment by longjie** [comment]
Sorry for late response.
I tried correct command. The robot looks working fine.
However, starting nextage_ros_bridge_real.launch, I got error messages below. Some node dies. 

I have e-mailed diagnosis file which previously you asked.
Thank you.

```
tajima@nextage1:~$ roslaunch nextage_ros_bridge nextage_ros_bridge_real.launch MODEL_FILE:=/opt/jsk/etc/HIRONX/model/main.wrl
... logging to /home/tajima/.ros/log/18a71b3c-d2cb-11e4-b248-000bab77d7b5/roslaunch-nextage1-3622.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://nextage1:55450/

SUMMARY
========

PARAMETERS
 * /HrpsysSeqStateROSBridge/publish_sensor_transforms
 * /collision_state/comp_name
 * /controller_configuration
 * /diagnostic_aggregator/analyzers/computers/contains
 * /diagnostic_aggregator/analyzers/computers/path
 * /diagnostic_aggregator/analyzers/computers/type
 * /diagnostic_aggregator/analyzers/hrpsys/contains
 * /diagnostic_aggregator/analyzers/hrpsys/path
 * /diagnostic_aggregator/analyzers/hrpsys/type
 * /diagnostic_aggregator/analyzers/mode/contains
 * /diagnostic_aggregator/analyzers/mode/path
 * /diagnostic_aggregator/analyzers/mode/type
 * /diagnostic_aggregator/analyzers/motor/contains
 * /diagnostic_aggregator/analyzers/motor/path
 * /diagnostic_aggregator/analyzers/motor/type
 * /diagnostic_aggregator/base_path
 * /diagnostic_aggregator/pub_rate
 * /robot_description
 * /robot_pose_ekf/debug
 * /robot_pose_ekf/freq
 * /robot_pose_ekf/imu_used
 * /robot_pose_ekf/odom_used
 * /robot_pose_ekf/output_frame
 * /robot_pose_ekf/self_diagnose
 * /robot_pose_ekf/sensor_timeout
 * /robot_pose_ekf/vo_used
 * /rosdistro
 * /rosversion

NODES
  /
    CollisionDetectorComp (hrpsys/CollisionDetectorComp)
    DataLoggerServiceROSBridge (hrpsys_ros_bridge/DataLoggerServiceROSBridgeComp)
    ForwardKinematicsServiceROSBridge (hrpsys_ros_bridge/ForwardKinematicsServiceROSBridgeComp)
    HrpsysJointTrajectoryBridge (hrpsys_ros_bridge/HrpsysJointTrajectoryBridge)
    HrpsysSeqStateROSBridge (hrpsys_ros_bridge/HrpsysSeqStateROSBridge)
    RobotHardwareServiceROSBridge (hrpsys_ros_bridge/RobotHardwareServiceROSBridgeComp)
    SequencePlayerServiceROSBridge (hrpsys_ros_bridge/SequencePlayerServiceROSBridgeComp)
    StateHolderServiceROSBridge (hrpsys_ros_bridge/StateHolderServiceROSBridgeComp)
    base_footprint_rootlink (tf/static_transform_publisher)
    collision_state (hrpsys_ros_bridge/collision_state.py)
    diagnostic_aggregator (diagnostic_aggregator/aggregator_node)
    hrpsys_profile (hrpsys_ros_bridge/hrpsys_profile.py)
    hrpsys_py (hironx_ros_bridge/hironx.py)
    hrpsys_ros_diagnostics (hrpsys_ros_bridge/diagnostics.py)
    hrpsys_state_publisher (robot_state_publisher/state_publisher)
    robot_pose_ekf (robot_pose_ekf/robot_pose_ekf)
    rtmlaunch_collision_detector (openrtm_tools/rtmlaunch.py)
    rtmlaunch_hrpsys_ros_bridge (openrtm_tools/rtmlaunch.py)
    sensor_ros_bridge_connect (hrpsys_ros_bridge/sensor_ros_bridge_connect.py)

WARNING: unrecognized tag rtconnect
WARNING: unrecognized tag rtconnect
WARNING: unrecognized tag rtconnect
WARNING: unrecognized tag rtconnect
WARNING: unrecognized tag rtconnect
WARNING: unrecognized tag rtconnect
WARNING: unrecognized tag rtconnect
WARNING: unrecognized tag rtconnect
WARNING: unrecognized tag rtconnect
WARNING: unrecognized tag rtconnect
WARNING: unrecognized tag rtactivate
WARNING: unrecognized tag rtactivate
WARNING: unrecognized tag rtactivate
WARNING: unrecognized tag rtactivate
WARNING: unrecognized tag rtactivate
WARNING: unrecognized tag rtactivate
WARNING: unrecognized tag rtconnect
WARNING: unrecognized tag rtconnect
WARNING: unrecognized tag rtactivate
WARNING: unrecognized tag rtconnect
WARNING: unrecognized tag rtconnect
WARNING: unrecognized tag rtactivate
ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[hrpsys_py-1]: started with pid [3640]
process[HrpsysSeqStateROSBridge-2]: started with pid [3641]
process[HrpsysJointTrajectoryBridge-3]: started with pid [3673]
duplicated sensor Id is specified(id = 0, name = CAMERA_HEAD_R)
duplicated sensor Id is specified(id = 1, name = CAMERA_HEAD_L)
[ INFO] [1427273298.339890662]: [HrpsysJointTrajectoryBridge] @Initilize name : HrpsysJointTrajectoryBridge0 done
process[hrpsys_state_publisher-4]: started with pid [3695]
configuration ORB with  nextage : 15005
[hrpsys.py]  waiting ModelLoader
[hrpsys.py]  start hrpsys
[hrpsys.py]  finding RTCManager and RobotHardware
process[hrpsys_ros_diagnostics-5]: started with pid [3710]
process[diagnostic_aggregator-6]: started with pid [3715]
[ INFO] [1427273298.688886216]: [HrpsysSeqStateROSBridge] @Initilize name : HrpsysSeqStateROSBridge0
duplicated sensor Id is specified(id = 0, name = CAMERA_HEAD_R)
duplicated sensor Id is specified(id = 1, name = CAMERA_HEAD_L)
process[hrpsys_profile-7]: started with pid [3799]
[ INFO] [1427273298.775326639]: [HrpsysSeqStateROSBridge] Loaded HiroNX
[ INFO] [1427273298.777872110]: [HrpsysSeqStateROSBridge] @Initilize name : HrpsysSeqStateROSBridge0 done
process[sensor_ros_bridge_connect-8]: started with pid [3828]
[sensor_ros_bridge_connect.py]  start
configuration ORB with  nextage : 15005
process[rtmlaunch_hrpsys_ros_bridge-9]: started with pid [3835]
process[SequencePlayerServiceROSBridge-10]: started with pid [3846]
process[DataLoggerServiceROSBridge-11]: started with pid [3892]
[rtmlaunch] starting...  /opt/ros/hydro/share/hrpsys_ros_bridge/launch/hrpsys_ros_bridge.launch
[rtmlaunch] RTCTREE_NAMESERVERS nextage:15005 nextage:15005
[rtmlaunch] SIMULATOR_NAME RobotHardware0
[rtmlaunch] check connection/activation
process[ForwardKinematicsServiceROSBridge-12]: started with pid [3922]
[hrpsys.py]  wait for RTCmanager :  None
[hrpsys.py]  wait for RobotHardware  :  <hrpsys.rtm.RTcomponent instance at 0x3387d40> (timeout  0  < 10)
[hrpsys.py]  findComps -> RobotHardware :  <hrpsys.rtm.RTcomponent instance at 0x3387d40> isActive? =  True
[hrpsys.py]  simulation_mode :  False
[hrpsys.py]    bodyinfo URL = file:///opt/jsk/etc/HIRONX/model/main.wrl
process[StateHolderServiceROSBridge-13]: started with pid [3953]
process[RobotHardwareServiceROSBridge-14]: started with pid [3979]
[hrpsys.py]  creating components
process[robot_pose_ekf-15]: started with pid [4014]
process[base_footprint_rootlink-16]: started with pid [4051]
[sensor_ros_bridge_connect.py]  wait for RTCmanager :  nextage
[sensor_ros_bridge_connect.py]  wait for RobotHardware0  :  <hrpsys.rtm.RTcomponent instance at 0x12fa2d8> (timeout  0  < 10)
[sensor_ros_bridge_connect.py]  findComps -> RobotHardware :  <hrpsys.rtm.RTcomponent instance at 0x12fa2d8> isActive? =  True
[sensor_ros_bridge_connect.py]  simulation_mode :  False
[rtmlaunch] Connected from nextage:15005/RobotHardware0.rtc:q
[rtmlaunch]             to nextage:15005/HrpsysSeqStateROSBridge0.rtc:rsangle
[rtmlaunch]           with {'id': '', 'properties': {'dataport.publisher.push_policy': 'all', 'dataport.subscription_type': 'new'}, 'name': None, 'verbose': False}
process[CollisionDetectorComp-17]: started with pid [4071]
;;
;; Could not open /dev/console for writing.
;;
open: Permission denied
process[rtmlaunch_collision_detector-18]: started with pid [4079]
process[collision_state-19]: started with pid [4089]
prop[collision_pair] ->RARM_JOINT2:LARM_JOINT2 RARM_JOINT3:LARM_JOINT3 RARM_JOINT4:LARM_JOINT4 RARM_JOINT5:LARM_JOINT5
check collisions between RARM_JOINT2 and LARM_JOINT2
check collisions between RARM_JOINT3 and LARM_JOINT3
check collisions between RARM_JOINT4 and LARM_JOINT4
check collisions between RARM_JOINT5 and LARM_JOINT5
[rtmlaunch] starting...  /opt/ros/hydro/share/hrpsys_ros_bridge/launch/collision_detector.launch
[rtmlaunch] RTCTREE_NAMESERVERS nextage:15005 nextage:15005
[rtmlaunch] SIMULATOR_NAME RobotHardware0
[rtmlaunch] check connection/activation
[rtmlaunch] Connected from nextage:15005/RobotHardware0.rtc:tau
[rtmlaunch]             to nextage:15005/HrpsysSeqStateROSBridge0.rtc:rstorque
[rtmlaunch]           with {'id': '', 'properties': {'dataport.publisher.push_policy': 'all', 'dataport.subscription_type': 'new'}, 'name': None, 'verbose': False}
[sensor_ros_bridge_connect.py]   wait for  HrpsysSeqStateROSBridge0  :  <hrpsys.rtm.RTcomponent instance at 0x12facf8>
[rtmlaunch] Wait for  /nextage:15005/co.rtc:qCurrent   0 /30
configuration ORB with  nextage : 15005
[WARN] [WallTime: 1427273301.237870] Could not found CollisionDetector(co), waiting...
[rtmlaunch] Connected from nextage:15005/StateHolderServiceROSBridge.rtc:StateHolderService
[rtmlaunch]             to nextage:15005/sh.rtc:StateHolderService
[rtmlaunch]           with {'id': '', 'properties': {'dataport.publisher.push_policy': 'all', 'dataport.subscription_type': 'new'}, 'name': None, 'verbose': False}
[sensor_ros_bridge_connect.py]   wait for 'sh' :  <hrpsys.rtm.RTcomponent instance at 0x12faf80>
[sensor_ros_bridge_connect.py]    bodyinfo URL = file:///opt/jsk/etc/HIRONX/model/main.wrl
[sensor_ros_bridge_connect-8] process has finished cleanly
log file: /home/tajima/.ros/log/18a71b3c-d2cb-11e4-b248-000bab77d7b5/sensor_ros_bridge_connect-8*.log
[WARN] [WallTime: 1427273302.243693] Could not found CollisionDetector(co), waiting...
[rtmlaunch] Wait for  /nextage:15005/co.rtc:qCurrent   1 /30
[rtmlaunch] Connected from nextage:15005/sh.rtc:baseTformOut
[rtmlaunch]             to nextage:15005/HrpsysSeqStateROSBridge0.rtc:baseTform
[rtmlaunch]           with {'id': '', 'properties': {'dataport.publisher.push_policy': 'all', 'dataport.subscription_type': 'new'}, 'name': None, 'verbose': False}
[WARN] [WallTime: 1427273303.249335] Could not found CollisionDetector(co), waiting...
[hrpsys.py]    eval :  [self.seq, self.seq_svc, self.seq_version] = self.createComp("SequencePlayer","seq")
RTC named " seq " already exists.
[hrpsys.py]  create Comp ->  SequencePlayer  :  <hrpsys.rtm.RTcomponent instance at 0x30dd998>  ( 315.1.8 )
[hrpsys.py]  create CompSvc ->  SequencePlayer Service :  <OpenHRP._objref_SequencePlayerService instance at 0x3394ea8>
[hrpsys.py]    eval :  [self.sh, self.sh_svc, self.sh_version] = self.createComp("StateHolder","sh")
RTC named " sh " already exists.
[hrpsys.py]  create Comp ->  StateHolder  :  <hrpsys.rtm.RTcomponent instance at 0x3392a70>  ( 315.1.8 )
[hrpsys.py]  create CompSvc ->  StateHolder Service :  <OpenHRP._objref_StateHolderService instance at 0x3395cf8>
[hrpsys.py]    eval :  [self.fk, self.fk_svc, self.fk_version] = self.createComp("ForwardKinematics","fk")
RTC named " fk " already exists.
[hrpsys.py]  create Comp ->  ForwardKinematics  :  <hrpsys.rtm.RTcomponent instance at 0x3388560>  ( 315.1.8 )
[hrpsys.py]  create CompSvc ->  ForwardKinematics Service :  <OpenHRP._objref_ForwardKinematicsService instance at 0x33a27e8>
[hrpsys.py]    eval :  [self.ic, self.ic_svc, self.ic_version] = self.createComp("ImpedanceController","ic")
[rtmlaunch] Wait for  /nextage:15005/co.rtc:qCurrent   2 /30
[hrpsys.py]  create Comp ->  ImpedanceController  :  <hrpsys.rtm.RTcomponent instance at 0x339e0e0>  ( 315.1.8 )
[hrpsys.py]  create CompSvc ->  ImpedanceController Service :  <OpenHRP._objref_ImpedanceControllerService instance at 0x33a3128>
[hrpsys.py]    eval :  [self.el, self.el_svc, self.el_version] = self.createComp("SoftErrorLimiter","el")
RTC named " el " already exists.
[hrpsys.py]  create Comp ->  SoftErrorLimiter  :  <hrpsys.rtm.RTcomponent instance at 0x3396998>  ( 315.1.8 )
[hrpsys.py]  create CompSvc ->  SoftErrorLimiter Service :  <OpenHRP._objref_SoftErrorLimiterService instance at 0x33945a8>
[hrpsys.py]    eval :  [self.sc, self.sc_svc, self.sc_version] = self.createComp("ServoController","sc")
[hrpsys.py]  create Comp ->  ServoController  :  <hrpsys.rtm.RTcomponent instance at 0x339d5a8>  ( 315.1.8 )
[hrpsys.py]  create CompSvc ->  ServoController Service :  <OpenHRP._objref_ServoControllerService instance at 0x339ea28>
[hrpsys.py]    eval :  [self.log, self.log_svc, self.log_version] = self.createComp("DataLogger","log")
RTC named " log " already exists.
[hrpsys.py]  create Comp ->  DataLogger  :  <hrpsys.rtm.RTcomponent instance at 0x33964d0>  ( 315.1.8 )
[hrpsys.py]  create CompSvc ->  DataLogger Service :  <OpenHRP._objref_DataLoggerService instance at 0x3398d88>
[hrpsys.py]    eval :  [self.rmfo, self.rmfo_svc, self.rmfo_version] = self.createComp("RemoveForceSensorLinkOffset","rmfo")
[rtmlaunch] Connected from nextage:15005/sh.rtc:qOut
[rtmlaunch]             to nextage:15005/HrpsysSeqStateROSBridge0.rtc:mcangle
[rtmlaunch]           with {'id': '', 'properties': {'dataport.publisher.push_policy': 'all', 'dataport.subscription_type': 'new'}, 'name': None, 'verbose': False}
[hrpsys.py]  Fail to createComps 'NoneType' object has no attribute 'ref' 
[hrpsys.py]  connecting components
[rtm.py]    Connect sh.qOut - ic.qRef
[rtm.py]    Connect ic.q - el.qRef
el.q and RobotHardware0.qRef are already connected
RobotHardware0.servoState and el.servoStateIn are already connected
RobotHardware0.q and sh.currentQIn are already connected
RobotHardware0.q and fk.q are already connected
sh.qOut and fk.qRef are already connected
seq.qRef and sh.qIn are already connected
seq.tqRef and sh.tqIn are already connected
seq.basePos and sh.basePosIn are already connected
seq.baseRpy and sh.baseRpyIn are already connected
seq.zmpRef and sh.zmpIn are already connected
[rtm.py]    Failed to connect None to [None]
sh.basePosOut and seq.basePosInit are already connected
sh.basePosOut and fk.basePosRef are already connected
sh.baseRpyOut and seq.baseRpyInit are already connected
sh.baseRpyOut and fk.baseRpyRef are already connected
sh.qOut and seq.qInit are already connected
[rtm.py]    Failed to connect sh.zmpOut to None
[WARN] [WallTime: 1427273304.253967] Could not found CollisionDetector(co), waiting...
[rtm.py]    Connect RobotHardware0.q - ic.qCurrent
[rtm.py]    Failed to connect sh.basePosOut to None
[rtm.py]    Failed to connect sh.baseRpyOut to None
RobotHardware0.q and el.qCurrent are already connected
[hrpsys.py]  activating components
[rtmlaunch] Connected from nextage:15005/HrpsysSeqStateROSBridge0.rtc:SequencePlayerService
[rtmlaunch]             to nextage:15005/seq.rtc:SequencePlayerService
[rtmlaunch]           with {'id': '', 'properties': {'dataport.publisher.push_policy': 'all', 'dataport.subscription_type': 'new'}, 'name': None, 'verbose': False}
already serialized
already serialized
already serialized
already serialized
already serialized
Traceback (most recent call last):
  File "/opt/ros/hydro/share/hironx_ros_bridge/scripts/hironx.py", line 75, in <module>
    robot.init(robotname=args.robot, url=args.modelfile)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/hironx_ros_bridge/hironx_client.py", line 124, in init
    HrpsysConfigurator.init(self, robotname=robotname, url=url)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/hrpsys/hrpsys_config.py", line 1748, in init
    self.activateComps()
  File "/opt/ros/hydro/lib/python2.7/dist-packages/hrpsys/hrpsys_config.py", line 444, in activateComps
    rtm.serializeComponents(rtcList)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/hrpsys/rtm.py", line 424, in serializeComponents
    if not ec._is_equivalent(rtc.ec):
AttributeError: 'NoneType' object has no attribute 'ec'
[rtmlaunch] Wait for  /nextage:15005/co.rtc:qCurrent   3 /30
[hrpsys_py-1] process has died [pid 3640, exit code 1, cmd /opt/ros/hydro/share/hironx_ros_bridge/scripts/hironx.py --host nextage --port 15005 --modelfile /opt/jsk/etc/HIRONX/model/main.wrl --robot RobotHardware __name:=hrpsys_py __log:=/home/tajima/.ros/log/18a71b3c-d2cb-11e4-b248-000bab77d7b5/hrpsys_py-1.log].
log file: /home/tajima/.ros/log/18a71b3c-d2cb-11e4-b248-000bab77d7b5/hrpsys_py-1*.log
[WARN] [WallTime: 1427273305.259821] Could not found CollisionDetector(co), waiting...
[rtmlaunch] Connected from nextage:15005/HrpsysJointTrajectoryBridge0.rtc:SequencePlayerService
[rtmlaunch]             to nextage:15005/seq.rtc:SequencePlayerService
[rtmlaunch]           with {'id': '', 'properties': {'dataport.publisher.push_policy': 'all', 'dataport.subscription_type': 'new'}, 'name': None, 'verbose': False}
[rtmlaunch] Wait for  /nextage:15005/co.rtc:qCurrent   4 /30
```

**Comment by 534o** [comment]
Sorry for inconvenience, It seems we have bugs need to be fixed, please try this

```
./hot_fix.sh start-jsk/rtmros_hironx 318
./hot_fix.sh start-jsk/rtmros_hironx 343
./hot_fix.sh fkanehiro/hrpsys-base 534 /opt/ros/hydro/lib/python2.7/dist-packages/hrpsys 2
```

to obrain `hot_fix.sh` program

```
wget https://gist.githubusercontent.com/534o/de86e3d4ebce1f9e932a/raw/b83618d6a94c2c083cdf22a1fd02d86b20023eb6/hot_fix.sh -O hot_fix.sh
chmod u+x hot_fix.sh
```

you can revert these patches (either intentionally  or accidentally) 

```
sudo apt-get install --reinstall ros-hydro-hrpsys
sudo apt-get install --reinstall ros-hydro-hironx-ros-bridge
```

-- your friendly neighborhood  TORK dev team

**Comment by longjie** [comment]
Some warnings and errors (red text in console) remains, but are'nt they critical?
If not so, I believe the hotfixes solved the error. Thank you!

```
tajima@nextage1:~/Codes/ros/hydro$ roslaunch nextage_ros_bridge nextage_ros_brid
ge_real.launch MODEL_FILE:=/opt/jsk/etc/HIRONX/model/main.wrl
```

First warnings:

```
WARNING: unrecognized tag rtconnect
WARNING: unrecognized tag rtconnect
WARNING: unrecognized tag rtconnect
WARNING: unrecognized tag rtconnect
WARNING: unrecognized tag rtconnect
WARNING: unrecognized tag rtconnect
WARNING: unrecognized tag rtconnect
WARNING: unrecognized tag rtconnect
WARNING: unrecognized tag rtconnect
WARNING: unrecognized tag rtconnect
WARNING: unrecognized tag rtactivate
WARNING: unrecognized tag rtactivate
WARNING: unrecognized tag rtactivate
WARNING: unrecognized tag rtactivate
WARNING: unrecognized tag rtactivate
WARNING: unrecognized tag rtactivate
WARNING: unrecognized tag rtconnect
WARNING: unrecognized tag rtconnect
```

Second fail:

```
[hrpsys.py]    eval :  [self.rmfo, self.rmfo_svc, self.rmfo_version] = self.crea
teComp("AbsoluteForceSensor","rmfo")
[hrpsys.py]  Fail to createComps 'NoneType' object has no attribute 'ref' 
[hrpsys.py]  connecting components
```

Third fails:

```
[rtm.py]    Failed to connect None to [None]
sh.basePosOut and seq.basePosInit are already connected
sh.basePosOut and fk.basePosRef are already connected
sh.baseRpyOut and seq.baseRpyInit are already connected
sh.baseRpyOut and fk.baseRpyRef are already connected
sh.qOut and seq.qInit are already connected
process[base_footprint_rootlink-17]: started with pid [9585]
[rtm.py]    Failed to connect sh.zmpOut to None
RobotHardware0.q and ic.qCurrent are already connected
[rtm.py]    Failed to connect sh.basePosOut to None
[sensor_ros_bridge_connect.py]  wait for RTCmanager :  nextage
[rtm.py]    Failed to connect sh.baseRpyOut to None
RobotHardware0.q and el.qCurrent are already connected
[hrpsys.py]  activating components
[sensor_ros_bridge_connect.py]  wait for RobotHardware0  :  <hrpsys.rtm.RTcompon
ent instance at 0x23f7440> (timeout  0  < 10)
[sensor_ros_bridge_connect.py]  findComps -> RobotHardware :  <hrpsys.rtm.RTcomp
onent instance at 0x23f7440> isActive? =  True
[hrpsys.py]  Fail to find instance (['rmfo', 'AbsoluteForceSensor']) for getRTCI
nstanceList
```

Forth fail is:

```
[hrpsys.py]    setupLogger : record type = TimedLongSeqSeq , name =  servoState 
 to  RobotHardware0_servoState
[rtm.py]    Failed to connect RobotHardware0.servoState to None
[hrpsys.py]  setup joint groups
```

**Comment by 534o** [comment]
Warnings and errors are expected and critical for robots have force sensors, but if you does not have one, it is ok.
Does you robot working fine, after this patch?
-- your friendly neighborhood TORK dev team

**Comment by longjie** [comment]
Yes, it's working fine. Thank you for your effort.

**Comment by 130s** [comment]
Closing since no major dispute has been heard for awhile. Thank you for the attention and feedback (esp. @longjie).

**Comment by k-okada** [comment]
```
BEFORE ver. 0.6.0 roslaunch nextage_ros_bridge nextage_ros_bridge_real.launch
AFTER ver. 0.6.0 roslaunch nextage_ros_bridge nextage_ros_bridge_real.launch MODEL_FILE:=/opt/jsk/etc/HIRONX/model/main.wrl
```

why we have to change this? why we did not set default MODEL_FILE values?
